### ISSUE TITLE
HTML characters cause errors in ms_synthesize

### ISSUE THREAD

**Issue by revodavid** [muschellij2/mscstts#1]
The `<` in this call causes it to throw a "bad request" error:
```R
ms_synthesize("hello < dave", output_format = "audio-16khz-128kbitrate-mono-mp3")
```
You may need to sanitize the text input before sending it to the Bing Speech API. As a workaround, I just filtered my inputs with `gsub("[<>/]","",text)`.

**Comment by muschellij2** [comment]
Seems related to SSML spec in general: https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/issues/25.  I'll look into escaping things.  I will likely have an option for this.  One reason I don't want to auto-escape is that you could potentially put valid SSML in there and I'd want that option to work.

**Comment by muschellij2** [comment]
Please see `escape` argument now, which will do your subs, as well as `&` to "and", which may not be 100% of the desired behavior but probably is).  Using new dev version should work and I'll push to CRAN next week.
