### ISSUE TITLE
Error in my key or token when using mscstts

### ISSUE THREAD

**Issue by ManuelSpinola** [muschellij2/mscstts#4]
I signed with Microsoft Azure, but when I try to run de example from the mscstts package I got the following error.

> if (ms_have_tts_key()) {
+ res = ms_synthesize(
+ script = "hey, how are you doing? I'm doing pretty good",
+ output_format = "audio-16khz-128kbitrate-mono-mp3")
+ tmp <- tempfile(fileext = ".mp3")
+ writeBin(res$content, con = tmp)
+ mp3 = tuneR::readMP3(tmp)
+ }

Error in ms_get_tts_token(api_key = api_key) : Unauthorized (HTTP 401).

**Comment by muschellij2** [comment]
When you say you "signed with Microsoft Azure" - what do you mean?  Did you
set up an API key?   See
https://github.com/muschellij2/mscstts#getting-an-api-key
Best,
John

**Comment by ManuelSpinola** [comment]
Thank you very much John.

Yes, they gave me an api key and a token, but I don´t know how to use it.

Manuel

**Comment by muschellij2** [comment]
You're welcome, closing now.
